(()=>{
  const tg=window.Telegram?.WebApp;
  if(tg){tg.ready();tg.expand();try{tg.setHeaderColor('#07152a');tg.setBackgroundColor('#07152a')}catch(_){} }
  const I={
    tr:{back:'GAME CENTER',eyebrow:'GAME CENTER • KRİSTAL MAĞARASI',tagline:'Aynı kristalleri zincirle, nadir taşları patlat ve puanını büyüt.',wallet:'CÜZDAN',today:'BUGÜNKÜ KAZANÇ',score:'SKOR',huntTitle:'KRİSTAL ZİNCİRİ',hint:'Aynı renkte komşu kristallere dokun. Zinciri bitirince kristalleri topla.',ready:'HAZIR',playing:'AVLANIYOR...',chain:'ZİNCİR',moves:'HAMLE',start:'KRİSTALLERİ AÇ',collect:'ZİNCİRİ TOPLA',current:'SEÇİLİ ZİNCİR',rulesTitle:'KRİSTAL KURALLARI',rule1:'Aynı renkte komşu kristalleri art arda seç.',rule2:'Üçlü zincir puan verir; zincir uzadıkça çarpan artar.',rule3:'Nadir mor kristaller daha yüksek puan kazandırır.',rule4:'Yanlış renge dokunursan zincirin sıfırlanır.',target:'BUGÜNÜN HEDEFİ',finished:'KRİSTAL AVCISI TAMAMLANDI',earned:'Kazanılan ödül',again:'TEKRAR OYNA',adPlaceholder:'REKLAM ALANI',adNetwork:'AdsGram'},
    en:{back:'GAME CENTER',eyebrow:'GAME CENTER • CRYSTAL CAVE',tagline:'Chain matching crystals, crack rare gems and grow your score.',wallet:'WALLET',today:"TODAY'S EARNINGS",score:'SCORE',huntTitle:'CRYSTAL CHAIN',hint:'Tap neighboring crystals of the same color. Collect when your chain is ready.',ready:'READY',playing:'HUNTING...',chain:'CHAIN',moves:'MOVES',start:'OPEN CRYSTALS',collect:'COLLECT CHAIN',current:'CURRENT CHAIN',rulesTitle:'CRYSTAL RULES',rule1:'Pick neighboring crystals with the same color.',rule2:'Three or more gives points; longer chains raise the multiplier.',rule3:'Rare purple crystals are worth more.',rule4:'Touching a different color breaks your chain.',target:"TODAY'S TARGET",finished:'CRYSTAL HUNT COMPLETE',earned:'Reward earned',again:'PLAY AGAIN',adPlaceholder:'AD AREA',adNetwork:'AdsGram'},
    ru:{back:'GAME CENTER',eyebrow:'GAME CENTER • ХРУСТАЛЬНАЯ ПЕЩЕРА',tagline:'Соединяй кристаллы, добывай редкие камни и набирай очки.',wallet:'КОШЕЛЕК',today:'ЗАРАБОТОК СЕГОДНЯ',score:'СЧЕТ',huntTitle:'КРИСТАЛЬНАЯ ЦЕПОЧКА',hint:'Выбирай соседние кристаллы одного цвета. Собери цепь и забери её.',ready:'ГОТОВО',playing:'ОХОТА...',chain:'ЦЕПОЧКА',moves:'ХОДЫ',start:'ОТКРЫТЬ КРИСТАЛЛЫ',collect:'СОБРАТЬ ЦЕПОЧКУ',current:'ТЕКУЩАЯ ЦЕПОЧКА',rulesTitle:'ПРАВИЛА КРИСТАЛЛОВ',rule1:'Выбирай соседние кристаллы одного цвета.',rule2:'От трёх кристаллов идут очки; длинная цепь повышает множитель.',rule3:'Редкие фиолетовые кристаллы дают больше.',rule4:'Другой цвет сбивает цепочку.',target:'ЦЕЛЬ НА СЕГОДНЯ',finished:'ОХОТА ЗАВЕРШЕНА',earned:'Награда',again:'ИГРАТЬ СНОВА',adPlaceholder:'РЕКЛАМНЫЙ БЛОК',adNetwork:'AdsGram'},
    es:{back:'GAME CENTER',eyebrow:'GAME CENTER • CUEVA DE CRISTALES',tagline:'Encadena cristales, rompe gemas raras y aumenta tu puntuación.',wallet:'BILLETERA',today:'GANANCIAS DE HOY',score:'PUNTOS',huntTitle:'CADENA DE CRISTALES',hint:'Toca cristales vecinos del mismo color. Recoge la cadena cuando esté lista.',ready:'LISTO',playing:'BUSCANDO...',chain:'CADENA',moves:'MOVIMIENTOS',start:'ABRIR CRISTALES',collect:'RECOGER CADENA',current:'CADENA ACTUAL',rulesTitle:'REGLAS DE CRISTALES',rule1:'Elige cristales vecinos del mismo color.',rule2:'Tres o más dan puntos; las cadenas largas suben el multiplicador.',rule3:'Los cristales morados raros valen más.',rule4:'Otro color rompe la cadena.',target:'OBJETIVO DE HOY',finished:'CAZA COMPLETADA',earned:'Recompensa',again:'JUGAR DE NUEVO',adPlaceholder:'ÁREA DE ANUNCIO',adNetwork:'AdsGram'},
    de:{back:'GAME CENTER',eyebrow:'GAME CENTER • KRISTALLHÖHLE',tagline:'Verbinde Kristalle, knacke seltene Steine und erhöhe deinen Score.',wallet:'GUTHABEN',today:'HEUTIGER VERDIENST',score:'PUNKTE',huntTitle:'KRISTALLKETTE',hint:'Tippe benachbarte Kristalle derselben Farbe an und sammle die Kette.',ready:'BEREIT',playing:'SUCHE...',chain:'KETTE',moves:'ZÜGE',start:'KRISTALLE ÖFFNEN',collect:'KETTE SAMMELN',current:'AKTUELLE KETTE',rulesTitle:'KRISTALLREGELN',rule1:'Wähle benachbarte Kristalle derselben Farbe.',rule2:'Drei oder mehr geben Punkte; lange Ketten erhöhen den Multiplikator.',rule3:'Seltene violette Kristalle sind mehr wert.',rule4:'Eine andere Farbe bricht die Kette.',target:'HEUTIGES ZIEL',finished:'KRISTALLJAGD BEENDET',earned:'Belohnung',again:'NOCHMAL SPIELEN',adPlaceholder:'WERBEBEREICH',adNetwork:'AdsGram'}
  };
  let lang=(localStorage.getItem('mm_language')||tg?.initDataUnsafe?.user?.language_code||'tr').slice(0,2).toLowerCase();if(!I[lang])lang='tr';let T=I[lang];
  const $=id=>document.getElementById(id),BAL='gc_local_balance',TODAY='gc_local_today',CRYSTAL='gc_crystal_today',LIMIT=.001;
  const money=n=>'$'+Number(n||0).toFixed(5),get=k=>Number(localStorage.getItem(k)||0);
  const colors=['cyan','blue','pink','purple','gold'];
  const glyph={cyan:'◆',blue:'◇',pink:'✦',purple:'⬥',gold:'✧'};
  let game={running:false,starting:false,board:[],chain:[],moves:18,score:0,sessionId:null,startedAt:0};
  function apply(){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(e=>{if(T[e.dataset.i18n])e.textContent=T[e.dataset.i18n]});document.querySelectorAll('[data-game-i18n]').forEach(e=>{if(T[e.dataset.gameI18n])e.textContent=T[e.dataset.gameI18n]});$('langBtn').textContent=lang.toUpperCase()}
  function render(){const b=window.GameCenterWallet.getBalance(),d=window.GameCenterWallet.getToday(),g=window.GameCenterWallet.getGameToday('crystal_hunt');$('wallet').textContent=money(b);$('today').textContent=money(d);$('score').textContent=game.score;$('chain').textContent=game.chain.length;$('moves').textContent=game.moves;$('movesFill').style.width=(game.moves/18*100)+'%';$('targetText').textContent=money(Math.min(g,LIMIT))+' / $0.00100';$('targetBar').style.width=Math.min(100,g/LIMIT*100)+'%';$('currentText').textContent=game.chain.length?game.chain.length+' '+T.chain:'—'}
  const idx=(r,c)=>r*6+c, rc=i=>[Math.floor(i/6),i%6];
  function adjacent(a,b){const [ar,ac]=rc(a),[br,bc]=rc(b);return Math.abs(ar-br)+Math.abs(ac-bc)===1}
  function makeBoard(){game.board=Array.from({length:36},()=>colors[Math.floor(Math.random()*colors.length)]);game.chain=[];const board=$('board');board.innerHTML='';game.board.forEach((color,i)=>{const cell=document.createElement('button');cell.className='ch-cell '+color;cell.type='button';cell.dataset.i=i;cell.textContent=glyph[color];cell.addEventListener('click',()=>pick(i));board.appendChild(cell)})}
  function updateSelection(){document.querySelectorAll('.ch-cell').forEach(c=>c.classList.toggle('selected',game.chain.includes(Number(c.dataset.i))))}
  function pick(i){if(!game.running)return;const color=game.board[i],last=game.chain.at(-1);if(game.chain.includes(i))return;if(last===undefined){game.chain=[i]}else if(adjacent(last,i)&&game.board[last]===color){game.chain.push(i)}else if(adjacent(last,i)){game.chain=[];game.chain=[i]}else{return}updateSelection();$('collectBtn').disabled=game.chain.length<3;render()}
  function collect(){if(!game.running||game.chain.length<3)return;const len=game.chain.length,color=game.board[game.chain[0]],rare=color==='purple';const mult=Math.min(6,1+Math.floor((len-3)/2));const base=rare?20:10;game.score+=base*len*mult;game.chain.forEach(i=>{$('board').children[i].classList.add('pop','locked');$('board').children[i].disabled=true});game.moves--;game.chain=[];$('collectBtn').disabled=true;setTimeout(()=>{if(game.moves<=0)finish();else{game.board.forEach((_,i)=>{if($('board').children[i].classList.contains('locked')){const nc=colors[Math.floor(Math.random()*colors.length)];game.board[i]=nc;const cell=$('board').children[i];cell.className='ch-cell '+nc;cell.textContent=glyph[nc];cell.disabled=false}});updateSelection();render()}},180);render()}
  async function finish(){if(game.finishing)return;game.finishing=true;game.running=false;document.querySelectorAll('.ch-cell').forEach(c=>c.disabled=true);const requested=Math.min(.001,Math.max(0,game.score)*.0000045);let reward=0;const elapsed=Date.now()-game.startedAt;const wait=Math.max(0,28000-elapsed);if(wait)await new Promise(r=>setTimeout(r,wait)); try { const data=await window.GameCenterWallet.complete('crystal_hunt',game.sessionId,requested); reward=Number(data.awarded||0); } catch(e) { reward=0; game.error=e.message; }$('state').innerHTML='<i></i><span>'+T.ready+'</span>';$('startBtn').disabled=false;$('finalScore').textContent=game.score;$('reward').textContent=money(reward);$('result').hidden=false;render()}
  async function start(){if(game?.starting||game?.running)return; game.starting=true; $('result').hidden=true; const session=await window.GameCenterWallet.start('crystal_hunt').catch(e=>({ok:false,message:e.message})); if(!session.ok){game={running:false,starting:false,board:[],chain:[],moves:18,score:0,sessionId:null,startedAt:0};alert(session.message||'Game Center unavailable');return;} game={running:true,starting:false,finishing:false,board:[],chain:[],moves:18,score:0,sessionId:session.sessionId,startedAt:Date.now()};makeBoard();$('state').innerHTML='<i></i><span>'+T.playing+'</span>';$('startBtn').disabled=true;$('collectBtn').disabled=true;render()}
  $('startBtn').addEventListener('click',start);$('collectBtn').addEventListener('click',collect);$('againBtn').addEventListener('click',start);$('langBtn').addEventListener('click',()=>{const o=['tr','en','ru','es','de'];lang=o[(o.indexOf(lang)+1)%o.length];T=I[lang];localStorage.setItem('mm_language',lang);apply();render()});
  apply();render();
})();
