(()=>{
  const tg=window.Telegram?.WebApp;
  if(tg){tg.ready();tg.expand();try{tg.setHeaderColor('#06121a');tg.setBackgroundColor('#06121a')}catch(_){} }
  const I={
    tr:{back:'GAME CENTER',eyebrow:'GAME CENTER • ALTIN MADENİ',tagline:'Altınları topla, kayalardan kaç ve en yüksek skoru yakala.',wallet:'CÜZDAN',today:'BUGÜNKÜ KAZANÇ',score:'SKOR',mineTitle:'ALTIN AVI',mineHint:'Parlayan alanları aç. Altın ve sandık buldukça puanın yükselir.',ready:'HAZIR',playing:'MADENDE...',combo:'KOMBO',found:'ALTIN',start:'MADENE GİR',fair:'Ödül ve günlük limitler Game Center kurallarına bağlıdır.',rulesTitle:'MADEN KURALLARI',rule1:'Altınları açarak puanını artır.',rule2:'Kayalar kombo zincirini bozar.',rule3:'Sandıklar ekstra puan kazandırır.',rule4:'Arka arkaya doğru seçimler çarpanı büyütür.',targetTitle:'BUGÜNÜN HEDEFİ',finished:'MADEN TURU TAMAMLANDI',earned:'Kazanılan ödül',again:'TEKRAR OYNA',adPlaceholder:'REKLAM ALANI',adNetwork:'AdsGram'},
    en:{back:'GAME CENTER',eyebrow:'GAME CENTER • GOLD MINE',tagline:'Collect gold, avoid rocks and chase the highest score.',wallet:'WALLET',today:"TODAY'S EARNINGS",score:'SCORE',mineTitle:'GOLD HUNT',mineHint:'Open glowing tiles. Gold and chests increase your score.',ready:'READY',playing:'MINING...',combo:'COMBO',found:'GOLD',start:'ENTER MINE',fair:'Rewards and daily limits follow Game Center rules.',rulesTitle:'MINE RULES',rule1:'Open gold to increase your score.',rule2:'Rocks break your combo chain.',rule3:'Chests grant extra points.',rule4:'Consecutive correct picks increase your multiplier.',targetTitle:"TODAY'S TARGET",finished:'MINING RUN COMPLETE',earned:'Reward earned',again:'PLAY AGAIN',adPlaceholder:'AD AREA',adNetwork:'AdsGram'},
    ru:{back:'GAME CENTER',eyebrow:'GAME CENTER • ЗОЛОТАЯ ШАХТА',tagline:'Собирай золото, избегай камней и набирай максимум.',wallet:'КОШЕЛЕК',today:'ЗАРАБОТОК СЕГОДНЯ',score:'СЧЕТ',mineTitle:'ОХОТА ЗА ЗОЛОТОМ',mineHint:'Открывай сияющие клетки. Золото и сундуки дают очки.',ready:'ГОТОВО',playing:'ДОБЫЧА...',combo:'КОМБО',found:'ЗОЛОТО',start:'ВОЙТИ В ШАХТУ',fair:'Награды и дневные лимиты следуют правилам Game Center.',rulesTitle:'ПРАВИЛА ШАХТЫ',rule1:'Открывай золото и увеличивай счет.',rule2:'Камни сбивают комбо.',rule3:'Сундуки дают дополнительные очки.',rule4:'Серия точных ходов повышает множитель.',targetTitle:'ЦЕЛЬ НА СЕГОДНЯ',finished:'ЗАБЕГ ЗАВЕРШЕН',earned:'Награда',again:'ИГРАТЬ СНОВА',adPlaceholder:'РЕКЛАМНЫЙ БЛОК',adNetwork:'AdsGram'},
    es:{back:'GAME CENTER',eyebrow:'GAME CENTER • MINA DE ORO',tagline:'Recoge oro, evita las rocas y busca la mejor puntuación.',wallet:'BILLETERA',today:'GANANCIAS DE HOY',score:'PUNTOS',mineTitle:'CAZA DEL ORO',mineHint:'Abre las casillas brillantes. El oro y los cofres suman puntos.',ready:'LISTO',playing:'MINANDO...',combo:'COMBO',found:'ORO',start:'ENTRAR EN LA MINA',fair:'Las recompensas y límites siguen las reglas del Game Center.',rulesTitle:'REGLAS DE LA MINA',rule1:'Abre oro para aumentar tu puntuación.',rule2:'Las rocas rompen tu combo.',rule3:'Los cofres dan puntos extra.',rule4:'Las jugadas correctas consecutivas aumentan el multiplicador.',targetTitle:'OBJETIVO DE HOY',finished:'EXCURSIÓN COMPLETADA',earned:'Recompensa',again:'JUGAR DE NUEVO',adPlaceholder:'ÁREA DE ANUNCIO',adNetwork:'AdsGram'},
    de:{back:'GAME CENTER',eyebrow:'GAME CENTER • GOLDMINE',tagline:'Sammle Gold, meide Felsen und jag den Highscore.',wallet:'GUTHABEN',today:'HEUTIGER VERDIENST',score:'PUNKTE',mineTitle:'GOLDJAGD',mineHint:'Öffne leuchtende Felder. Gold und Truhen bringen Punkte.',ready:'BEREIT',playing:'ABBAU...',combo:'KOMBO',found:'GOLD',start:'IN DIE MINE',fair:'Belohnungen und Tageslimits folgen den Game-Center-Regeln.',rulesTitle:'MINENREGELN',rule1:'Öffne Gold und erhöhe deine Punkte.',rule2:'Felsen brechen deine Kombo.',rule3:'Truhen geben Extrapunkte.',rule4:'Aufeinanderfolgende Treffer erhöhen den Multiplikator.',targetTitle:'HEUTIGES ZIEL',finished:'LAUF ABGESCHLOSSEN',earned:'Belohnung',again:'NOCHMAL SPIELEN',adPlaceholder:'WERBEBEREICH',adNetwork:'AdsGram'}
  };
  let lang=(localStorage.getItem('mm_language')||tg?.initDataUnsafe?.user?.language_code||'tr').slice(0,2).toLowerCase();if(!I[lang])lang='tr';let T=I[lang];
  const apply=()=>{document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(e=>{if(T[e.dataset.i18n])e.textContent=T[e.dataset.i18n]});document.querySelectorAll('[data-game-i18n]').forEach(e=>{if(T[e.dataset.gameI18n])e.textContent=T[e.dataset.gameI18n]});document.getElementById('langBtn').textContent=lang.toUpperCase()};apply();
  const $=id=>document.getElementById(id), BAL='gc_local_balance',TODAY='gc_local_today',GOLD='gc_gold_today',LIMIT=.001;
  const money=n=>'$'+Number(n||0).toFixed(5);const get=k=>Number(localStorage.getItem(k)||0);
  let state={running:false,score:0,combo:1,gold:0,opened:0,timer:null};
  const pool=['gold','gold','gold','gold','gold','gold','gem','gem','chest','rock','rock','rock','rock','rock','rock','rock','rock','rock','rock','rock','gold','gold','gold','chest','rock'];
  function render(){const b=window.GameCenterWallet.getBalance(),d=window.GameCenterWallet.getToday(),g=window.GameCenterWallet.getGameToday('gold_rush');$('wallet').textContent=money(b);$('today').textContent=money(d);$('score').textContent=state.score;$('found').textContent=state.gold;$('combo').textContent='x'+state.combo;$('targetText').textContent=money(Math.min(g,LIMIT))+' / $0.00100';$('targetBar').style.width=Math.min(100,g/LIMIT*100)+'%'}
  function makeBoard(){const grid=$('mineGrid');grid.innerHTML='';const arr=[...pool].sort(()=>Math.random()-.5);arr.forEach((type,i)=>{const c=document.createElement('button');c.className='gr-cell';c.type='button';c.textContent='?';c.dataset.type=type;c.dataset.i=i;c.setAttribute('aria-label','Gold Rush');c.onclick=()=>hit(c);grid.appendChild(c)})}
  function hit(c){if(!state.running||c.disabled)return;c.disabled=true;c.classList.add('hit',c.dataset.type);const type=c.dataset.type;c.textContent=type==='gold'?'🪙':type==='gem'?'💎':type==='chest'?'🎁':'🪨';state.opened++;if(type==='gold'){state.gold++;state.combo=Math.min(8,state.combo+1);state.score+=10*state.combo}else if(type==='gem'){state.combo=Math.min(8,state.combo+1);state.score+=18*state.combo}else if(type==='chest'){state.combo=Math.min(8,state.combo+2);state.score+=35*state.combo}else{state.combo=1;state.score=Math.max(0,state.score-5)}$('progressBar').style.width=(state.opened/25*100)+'%';render();if(state.opened>=25)finish()}
  async function finish(){if(!state.running)return;state.running=false;clearTimeout(state.timer);document.querySelectorAll('.gr-cell').forEach(c=>c.disabled=true);const requested=Math.min(.001,Math.max(0,state.score)*.000005);let reward=0; try { const data=await window.GameCenterWallet.complete('gold_rush',state.sessionId,requested); reward=Number(data.awarded||0); } catch(e) { reward=0; state.error=e.message; }$('runState').innerHTML='<i></i><span>'+T.ready+'</span>';$('startBtn').disabled=false;$('finalScore').textContent=state.score;$('reward').textContent=money(reward);$('result').hidden=false;render()}
  async function start(){ if(state?.starting)return; state={starting:true}; $('result').hidden=true; const session=await window.GameCenterWallet.start('gold_rush').catch(e=>({ok:false,message:e.message})); if(!session.ok){ state={starting:false,running:false,score:0,combo:1,gold:0,opened:0,timer:null}; alert(session.message||'Game Center unavailable'); return; } state={running:true,score:0,combo:1,gold:0,opened:0,timer:null};makeBoard();$('runState').innerHTML='<i></i><span>'+T.playing+'</span>';$('startBtn').disabled=true;$('progressBar').style.width='0%';render();state.sessionId=session.sessionId;state.timer=setTimeout(finish,30000)}
  $('startBtn').addEventListener('click',start);$('againBtn').addEventListener('click',start);$('langBtn').addEventListener('click',()=>{const order=['tr','en','ru','es','de'];lang=order[(order.indexOf(lang)+1)%order.length];T=I[lang];localStorage.setItem('mm_language',lang);apply();render()});render();
})();
