(() => {
  const tg=window.Telegram?.WebApp; if(tg){tg.ready();tg.expand();try{tg.setHeaderColor('#070b22');tg.setBackgroundColor('#070b22')}catch(e){}}
  const I={
    tr:{back:'← GAME CENTER',ad:'REKLAM ALANI',network:'AdsGram',title:'MINESWEEPER',subtitle:'Mayınları bul, güvenli hücreleri aç ve ödülünü kazan.',mines:'MAYIN',flags:'İŞARET',scoreLabel:'SKOR',wallet:'GAME CENTER CÜZDANI',plays:'BUGÜN KALAN OYUN',reward:'KAZANÇ',ready:'HAZIR',safe:'GÜVENLİ HÜCRE',restart:'🔄 YENİ OYUN',flagMode:'🚩 İŞARETLEME',help:'Hücreyi açmak için dokun. Mayın olabileceğini düşündüğün hücreyi işaretlemek için İşaretle modunu kullan.',playAgain:'TEKRAR OYNA',winTitle:'TEBRİKLER!',winText:'Tüm güvenli hücreleri açtın. Ödülün cüzdanına eklendi.',loseTitle:'MAYINA BASTIN!',loseText:'Mayınlardan biri açıldı. Tekrar deneyebilirsin.',limitTitle:'BUGÜNKÜ OYUN HAKKIN BİTTİ',limitText:'Bugünkü Minesweeper hakkın doldu. Yarın tekrar oynayabilirsin.'},
    en:{back:'← GAME CENTER',ad:'AD SPACE',network:'AdsGram',title:'MINESWEEPER',subtitle:'Find the mines, clear safe cells and earn your reward.',mines:'MINES',flags:'FLAGS',scoreLabel:'SCORE',wallet:'GAME CENTER WALLET',plays:'PLAYS LEFT TODAY',reward:'REWARD',ready:'READY',safe:'SAFE CELLS',restart:'🔄 NEW GAME',flagMode:'🚩 FLAG MODE',help:'Tap a cell to open it. Use Flag Mode to mark cells you think may contain a mine.',playAgain:'PLAY AGAIN',winTitle:'CONGRATULATIONS!',winText:'You cleared every safe cell. Your reward was added to the wallet.',loseTitle:'BOOM!',loseText:'You hit a mine. Try again.',limitTitle:'NO PLAYS LEFT TODAY',limitText:'Your Minesweeper plays for today are finished. Come back tomorrow.'},
    ru:{back:'← GAME CENTER',ad:'РЕКЛАМНОЕ МЕСТО',network:'AdsGram',title:'САПЁР',subtitle:'Найди мины, открой безопасные клетки и получи награду.',mines:'МИНЫ',flags:'ФЛАГИ',scoreLabel:'ОЧКИ',wallet:'КОШЕЛЁК GAME CENTER',plays:'ИГР ОСТАЛОСЬ',reward:'НАГРАДА',ready:'ГОТОВО',safe:'БЕЗОПАСНЫЕ КЛЕТКИ',restart:'🔄 НОВАЯ ИГРА',flagMode:'🚩 ФЛАГ',help:'Нажми на клетку, чтобы открыть её. Используй режим флага для отметки возможных мин.',playAgain:'ИГРАТЬ СНОВА',winTitle:'ПОЗДРАВЛЯЕМ!',winText:'Все безопасные клетки открыты. Награда добавлена в кошелёк.',loseTitle:'ВЗРЫВ!',loseText:'Ты открыл мину. Попробуй ещё раз.',limitTitle:'ИГР БОЛЬШЕ НЕТ',limitText:'Лимит игр на сегодня исчерпан. Возвращайся завтра.'},
    es:{back:'← GAME CENTER',ad:'ESPACIO PUBLICITARIO',network:'AdsGram',title:'BUSCAMINAS',subtitle:'Encuentra las minas, abre las casillas seguras y gana.',mines:'MINAS',flags:'BANDERAS',scoreLabel:'PUNTOS',wallet:'BILLETERA GAME CENTER',plays:'PARTIDAS RESTANTES',reward:'RECOMPENSA',ready:'LISTO',safe:'CASILLAS SEGURAS',restart:'🔄 NUEVA PARTIDA',flagMode:'🚩 MARCAR',help:'Toca una casilla para abrirla. Usa el modo marcar para señalar posibles minas.',playAgain:'JUGAR DE NUEVO',winTitle:'¡FELICIDADES!',winText:'Has abierto todas las casillas seguras. La recompensa se añadió a tu billetera.',loseTitle:'¡BOOM!',loseText:'Pisaste una mina. Inténtalo de nuevo.',limitTitle:'NO QUEDAN PARTIDAS',limitText:'Has terminado tus partidas de hoy. Vuelve mañana.'},
    de:{back:'← GAME CENTER',ad:'WERBEFLÄCHE',network:'AdsGram',title:'MINESWEEPER',subtitle:'Finde die Minen, öffne sichere Felder und verdiene deine Belohnung.',mines:'MINEN',flags:'MARKIERUNGEN',scoreLabel:'PUNKTE',wallet:'GAME CENTER WALLET',plays:'SPIELE ÜBRIG',reward:'BELOHNUNG',ready:'BEREIT',safe:'SICHERE FELDER',restart:'🔄 NEUES SPIEL',flagMode:'🚩 MARKIEREN',help:'Tippe auf ein Feld. Nutze den Markiermodus für vermutete Minen.',playAgain:'NOCHMAL SPIELEN',winTitle:'GLÜCKWUNSCH!',winText:'Alle sicheren Felder sind geöffnet. Die Belohnung wurde gutgeschrieben.',loseTitle:'BOOM!',loseText:'Du hast eine Mine getroffen. Versuch es erneut.',limitTitle:'KEINE SPIELE MEHR',limitText:'Deine heutigen Spiele sind aufgebraucht. Komm morgen wieder.'}
  };
  const raw=localStorage.getItem('mm_language')||tg?.initDataUnsafe?.user?.language_code||'tr', lang=String(raw).slice(0,2).toLowerCase(), t=I[lang]||I.tr;
  document.documentElement.lang=I[lang]?lang:'tr'; document.querySelectorAll('[data-ms]').forEach(e=>{const k=e.dataset.ms;if(t[k])e.textContent=t[k]});

  const SIZE=8, MINES=5, REWARD=.00020, MAX_PLAYS=3, MIN_SESSION_MS=28000, BAL='gc_local_balance', PLAYKEY='ms_daily_plays'; let sessionId=null,startedAt=0;
  const $=id=>document.getElementById(id), board=$('board'); let cells=[], mines=new Set(), opened=0, flags=0, finished=false, flagMode=false;
  const dayKey=()=>{const d=new Date();return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`};
  let usage=JSON.parse(localStorage.getItem(PLAYKEY)||'{}'); if(usage.day!==dayKey())usage={day:dayKey(),count:0};
  const balance=()=>window.GameCenterWallet.getBalance();
  const renderWallet=()=>{$('walletBalance').textContent=balance().toFixed(5);$('playsLeft').textContent=Math.max(0,MAX_PLAYS-usage.count)};
  const neighbors=i=>{const x=i%SIZE,y=Math.floor(i/SIZE),a=[];for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy)continue;const X=x+dx,Y=y+dy;if(X>=0&&X<SIZE&&Y>=0&&Y<SIZE)a.push(Y*SIZE+X)}return a};
  const addReward=async()=>{const wait=Math.max(0,MIN_SESSION_MS-(Date.now()-startedAt));if(wait)await new Promise(r=>setTimeout(r,wait));try{const data=await window.GameCenterWallet.complete('minesweeper',sessionId,REWARD);renderWallet();return Number(data.awarded||0)}catch(e){renderWallet();return 0}};
  async function end(win){if(finished)return;finished=true;cells.forEach((e,i)=>{if(mines.has(i)){e.classList.add('mine');e.textContent='💣'}});if(win){await addReward();$('resultIcon').textContent='🏆';$('resultTitle').textContent=t.winTitle;$('resultText').textContent=t.winText;$('status').textContent='✓';}else{$('resultIcon').textContent='💥';$('resultTitle').textContent=t.loseTitle;$('resultText').textContent=t.loseText;$('status').textContent='×';}$('result').classList.remove('hidden');}
  function openCell(i){if(finished||cells[i].classList.contains('open')||cells[i].classList.contains('flagged'))return;if(mines.has(i)){cells[i].textContent='💣';end(false);return;}const stack=[i],seen=new Set();while(stack.length){const n=stack.pop();if(seen.has(n)||cells[n].classList.contains('open')||cells[n].classList.contains('flagged')||mines.has(n))continue;seen.add(n);cells[n].classList.add('open','safe-good');opened++;const count=neighbors(n).filter(x=>mines.has(x)).length;cells[n].textContent=count||'';if(count)cells[n].classList.add('ms-n'+Math.min(4,count));else neighbors(n).forEach(x=>{if(!seen.has(x))stack.push(x)});} $('score').textContent=opened;if(opened===SIZE*SIZE-MINES)end(true);$('safeCount').textContent=SIZE*SIZE-MINES-opened;}
  function toggleFlag(i){if(finished||cells[i].classList.contains('open'))return;cells[i].classList.toggle('flagged');const on=cells[i].classList.contains('flagged');cells[i].textContent=on?'🚩':'';flags+=on?1:-1;$('flagCount').textContent=flags;}
  async function start(){
    if(usage.count>=MAX_PLAYS){$('status').textContent='×';$('resultIcon').textContent='🔒';$('resultTitle').textContent=t.limitTitle;$('resultText').textContent=t.limitText;$('result').classList.remove('hidden');return;}
    const session=await window.GameCenterWallet.start('minesweeper').catch(e=>({ok:false,message:e.message})); if(!session.ok){$('status').textContent='×';$('resultIcon').textContent='🔒';$('resultTitle').textContent='GAME CENTER';$('resultText').textContent=session.message||'Game Center unavailable.';$('result').classList.remove('hidden');return;} sessionId=session.sessionId; startedAt=Date.now(); usage.count++;localStorage.setItem(PLAYKEY,JSON.stringify(usage));renderWallet();finished=false;opened=0;flags=0;flagMode=false;$('flagMode').classList.remove('active');$('flagCount').textContent='0';$('score').textContent='0';$('safeCount').textContent=59;$('status').textContent=t.ready;$('result').classList.add('hidden');board.innerHTML='';cells=[];mines=new Set();while(mines.size<MINES)mines.add(Math.floor(Math.random()*64));for(let i=0;i<64;i++){const e=document.createElement('button');e.type='button';e.className='ms-cell';e.setAttribute('aria-label',`cell ${i+1}`);e.addEventListener('click',()=>flagMode?toggleFlag(i):openCell(i));e.addEventListener('contextmenu',ev=>{ev.preventDefault();toggleFlag(i)});board.appendChild(e);cells.push(e)}
  }
  $('restart').onclick=start;$('resultBtn').onclick=start;$('flagMode').onclick=()=>{if(finished)return;flagMode=!flagMode;$('flagMode').classList.toggle('active',flagMode)};renderWallet();start();
})();
