(() => {
  const tg=window.Telegram?.WebApp; if(tg){tg.ready();tg.expand();try{tg.setHeaderColor('#070b22');tg.setBackgroundColor('#070b22')}catch(e){}}
  const $=id=>document.getElementById(id);
  const tr={mission:'MADEN KOŞUSU',missionText:'Vagonunu raylarda yönlendir, altınları topla ve kayalara yakalanmadan mümkün olduğunca uzağa git.',score:'SKOR',distance:'MESAFE',combo:'KOMBO',collected:'TOPLANAN',best:'EN İYİ',how:'NASIL OYNANIR?',r1:'Altınları topla. Değerli yükler daha çok puan verir.',r2:'Kristalleri toplayınca kombo yükselir.',r3:'Kayalara çarpma. Zıplayarak veya şerit değiştirerek kaç.',r4:'Arka arkaya topladıkça çarpanın büyür.',session:'BU KOŞU',rewardText:'Koşu sonunda uygun ödül cüzdana eklenir.',ready:'HAZIR MISIN?',readyText:'Doğru şeride geç ve değerli yükleri kaçırma.',paused:'DURAKLATILDI',resume:'DEVAM ET',controls:'Şerit değiştirmek için kaydır veya ok tuşlarını kullan. Ortadaki butonla zıpla.'};
  const dict={tr:tr,en:{mission:'MINE RUN',missionText:'Steer your cart, collect valuable items and avoid rocks.',score:'SCORE',distance:'DISTANCE',combo:'COMBO',collected:'COLLECTED',best:'BEST',how:'HOW TO PLAY',r1:'Collect gold. Valuable items give more points.',r2:'Collect crystals to build your combo.',r3:'Avoid rocks by changing lanes or jumping.',r4:'Keep collecting to increase your multiplier.',session:'THIS RUN',rewardText:'The eligible reward is added to your wallet.',ready:'READY?',readyText:'Choose the right lane and grab the valuable loot.',paused:'PAUSED',resume:'RESUME',controls:'Swipe or use arrow keys to change lanes. Use the middle button to jump.'},ru:{mission:'ШАХТЁРСКИЙ ЗАБЕГ',missionText:'Управляй вагонеткой, собирай ценности и избегай камней.',score:'СЧЁТ',distance:'ДИСТАНЦИЯ',combo:'КОМБО',collected:'СОБРАНО',best:'РЕКОРД',how:'КАК ИГРАТЬ',r1:'Собирай золото. Ценные предметы дают больше очков.',r2:'Собирай кристаллы для комбо.',r3:'Избегай камней, меняя полосу или прыгая.',r4:'Собирай подряд, чтобы увеличить множитель.',session:'ЭТА ПОПЫТКА',rewardText:'Подходящая награда добавляется в кошелёк.',ready:'ГОТОВ?',readyText:'Выбери полосу и собирай ценные находки.',paused:'ПАУЗА',resume:'ПРОДОЛЖИТЬ',controls:'Свайпай или используй стрелки. Средняя кнопка — прыжок.'},es:{mission:'CARRERA MINERA',missionText:'Controla tu vagoneta, recoge tesoros y evita las rocas.',score:'PUNTOS',distance:'DISTANCIA',combo:'COMBO',collected:'RECOGIDO',best:'RÉCORD',how:'CÓMO JUGAR',r1:'Recoge oro. Los objetos valiosos dan más puntos.',r2:'Recoge cristales para aumentar el combo.',r3:'Evita rocas cambiando de carril o saltando.',r4:'Sigue recogiendo para aumentar el multiplicador.',session:'ESTA CARRERA',rewardText:'La recompensa válida se añade a tu cartera.',ready:'¿LISTO?',readyText:'Elige el carril correcto y recoge el botín.',paused:'PAUSA',resume:'CONTINUAR',controls:'Desliza o usa las flechas. El botón central sirve para saltar.'},de:{mission:'BERGBAHN-LAUF',missionText:'Steuere deinen Wagen, sammle Schätze und weiche Felsen aus.',score:'PUNKTE',distance:'STRECKE',combo:'KOMBO',collected:'GESAMMELT',best:'BESTE',how:'SO SPIELST DU',r1:'Sammle Gold. Wertvolle Gegenstände geben mehr Punkte.',r2:'Sammle Kristalle für deine Kombo.',r3:'Weiche Felsen durch Spurwechsel oder Sprünge aus.',r4:'Sammle weiter, um den Multiplikator zu erhöhen.',session:'DIESER LAUF',rewardText:'Die gültige Belohnung wird deiner Wallet gutgeschrieben.',ready:'BEREIT?',readyText:'Wähle die richtige Spur und sammle wertvolle Beute.',paused:'PAUSE',resume:'WEITER',controls:'Wische oder nutze die Pfeiltasten. Die mittlere Taste springt.'}};
  const raw=localStorage.getItem('mm_language')||tg?.initDataUnsafe?.user?.language_code||'en';const lang=String(raw).slice(0,2).toLowerCase();const L=dict[lang]||dict.en;document.documentElement.lang=lang;
  document.querySelectorAll('[data-i18n]').forEach(e=>{e.textContent=L[e.dataset.i18n]||e.textContent});
  const walletEl=$('wallet'),scoreEl=$('score'),distEl=$('distance'),comboEl=$('combo'),colEl=$('collected'),bestEl=$('best'),rewardEl=$('reward'),bar=$('progressBar'),stage=$('stage'),entities=$('entities'),cart=$('cart'),msg=$('stageMessage'),play=$('play'),pause=$('pauseShade'),resume=$('resume');
  const bestKey='miner_run_best';let sessionId=null;let balance=window.GameCenterWallet.getBalance(),today=window.GameCenterWallet.getToday(),best=Number(localStorage.getItem(bestKey)||0);bestEl.textContent=best;
  const fmt=n=>'$'+n.toFixed(5); const sync=()=>walletEl.textContent=fmt(balance); sync();
  let running=false,paused=false,lane=1,jumping=false,score=0,distance=0,combo=1,collected=0,reward=0,last=0,spawn=0,raf=0,entitiesList=[],startedAt=0,ending=false;
  const laneX=[23,50,77];
  function setCart(){cart.style.left=`calc(${laneX[lane]}% - 30px)`}
  function reset(){entities.innerHTML='';entitiesList=[];lane=1;jumping=false;score=0;distance=0;combo=1;collected=0;reward=0;spawn=0;scoreEl.textContent='0';distEl.textContent='0 m';comboEl.textContent='x1';colEl.textContent='0';rewardEl.textContent=fmt(0);bar.style.width='0%';setCart()}
  function spawnEntity(){const type=Math.random()<.14?'chest':Math.random()<.27?'rock':Math.random()<.22?'crystal':'coin';const el=document.createElement('div');el.className='entity '+type;el.textContent={coin:'🪙',crystal:'💎',rock:'🪨',chest:'🎁'}[type];const ln=Math.floor(Math.random()*3),x=laneX[ln];el.style.left=`calc(${x}% - 18px)`;el.style.top='-45px';entities.appendChild(el);entitiesList.push({el,type,lane:ln,y:-45,hit:false})}
  async function end(){if(ending)return;ending=true;running=false;cancelAnimationFrame(raf);const requested=Math.min(0.001,Math.max(0,score/300000));const wait=Math.max(0,28000-(Date.now()-startedAt));if(wait)await new Promise(r=>setTimeout(r,wait));try { const data=await window.GameCenterWallet.complete('miner_run',sessionId,requested); reward=Number(data.awarded||0); } catch(e) { reward=0; }balance=window.GameCenterWallet.getBalance();today=window.GameCenterWallet.getToday();if(score>best){best=score;localStorage.setItem(bestKey,best);bestEl.textContent=best}rewardEl.textContent=fmt(reward);sync();msg.style.display='flex';msg.querySelector('h2').textContent=reward>0?'RUN COMPLETE':'LIMIT REACHED';msg.querySelector('p').textContent=reward>0?`${score} ${L.score.toLowerCase()} • ${fmt(reward)}`:'Try again later.';play.textContent=(window.gameI18n?window.gameI18n('again'):'PLAY AGAIN');}
  function tick(ts){if(!running)return;if(paused){raf=requestAnimationFrame(tick);return}const dt=Math.min(34,ts-last||16);last=ts;distance+=dt*.035;distEl.textContent=Math.floor(distance)+' m';score+=Math.floor(dt*.012*combo);scoreEl.textContent=score;bar.style.width=Math.min(100,distance/2)+'%';spawn+=dt;if(spawn>520){spawn=0;spawnEntity()}const speed=.22+distance*.00045;for(let i=entitiesList.length-1;i>=0;i--){const o=entitiesList[i];o.y+=speed*dt;o.el.style.transform=`translateY(${o.y}px) rotate(${o.type==='coin'?o.y*1.5:0}deg)`;if(o.y>405){o.el.remove();entitiesList.splice(i,1);continue}const near=o.y>350&&o.y<420&&o.lane===lane;if(near&&!o.hit){o.hit=true;if(o.type==='rock'&&!jumping){combo=1;comboEl.textContent='x1';end();return}else if(o.type!=='rock'){const pts={coin:10,crystal:28,chest:55}[o.type];score+=pts*combo;collected++;combo=Math.min(8,combo+(o.type==='crystal'?1:0.25));combo=Math.round(combo*4)/4;scoreEl.textContent=score;comboEl.textContent='x'+combo;rewardEl.textContent=fmt(Math.min(.001,score/300000));o.el.remove();entitiesList.splice(i,1)}}}if(jumping){cart.style.transform='translateY(-48px)';setTimeout(()=>{if(running&&!paused){jumping=false;cart.style.transform=''}},320)}raf=requestAnimationFrame(tick)}
  async function start(){if(running)return; const session=await window.GameCenterWallet.start('miner_run').catch(e=>({ok:false,message:e.message})); if(!session.ok){alert(session.message||'Game Center unavailable');return;} sessionId=session.sessionId;reset();msg.style.display='none';ending=false;startedAt=Date.now();running=true;paused=false;last=performance.now();raf=requestAnimationFrame(tick)}
  function move(d){if(!running||paused)return;lane=Math.max(0,Math.min(2,lane+d));setCart()}
  play.onclick=start;resume.onclick=()=>{paused=false;pause.style.display='none'};document.querySelector('[data-dir="left"]').onclick=()=>move(-1);document.querySelector('[data-dir="right"]').onclick=()=>move(1);$('jump').onclick=()=>{if(running&&!paused&&!jumping){jumping=true}};
  document.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1);if(e.key==='ArrowUp'||e.key===' ')$('jump').click();if(e.key==='Escape'&&running){paused=!paused;pause.style.display=paused?'grid':'none'}});
  let sx=0,sy=0;stage.addEventListener('touchstart',e=>{const t=e.changedTouches[0];sx=t.clientX;sy=t.clientY},{passive:true});stage.addEventListener('touchend',e=>{const t=e.changedTouches[0],dx=t.clientX-sx,dy=t.clientY-sy;if(Math.abs(dx)>30&&Math.abs(dx)>Math.abs(dy))move(dx>0?1:-1);else if(dy<-30)$('jump').click()},{passive:true});
  setCart();
})();
